### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [mu-fazil-vk/FluxTube#1]
There's a little problem with your [app versioning](https://github.com/mu-fazil-vk/FluxTube/blob/main/pubspec.yaml#L6). As you always use the same `versionCode` (the `+1` in the linked `pubspec.yaml`, updates will never reach their recipients, as Android will always assume "I already have that version". So can you please make sure to always increase the number behind the `+` when you make a new release – starting with the next one? Thanks!

While being here, my scanners reported some other findings, too:

```
Dangerous flags:
----------------
* usesCleartextTraffic

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

May I ask what `usesCleartextTraffic` is needed/used for? By its description, the app is a client for YouTube. Well, by its description it uses the Piped API – so I assume this is to access Piped instances self-hosted in the local network?

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided by a little addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

----

That said, I've just set up your app to appear on the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) later today (assuming you will solve above issues with the next release). So be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to add e.g. to your Readme (next to the Github badge) and [link here](https://apt.izzysoft.de/packages/com.fazilvk.fluxtube) :smiley:

I saw you also applied for listing at F-Droid.org. You'll be asked there to add Fastlane structures here. If you want, I can send you a PR for that, as those structures have been set up with IzzyOnDroid already by now.

**Comment by mu-fazil-vk** [comment]
Thank you for bringing these issues to my attention. I will fix them and make a release as soon as possible. I gladly welcome your PR for setting up Fastlane structures in this project.

**Comment by mu-fazil-vk** [comment]
Just released [released](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.6.7) the new version with the fixes.

**Comment by IzzySoft** [comment]
Thanks! I can confirm both, the signing blob and cleartextTraffic being gone. And the offered PR is open now :smiley:

**Comment by shuvashish76** [comment]
The license is GPL v3 or AGPL v3? Please fix the shield badge & link in "readme".

**Comment by mu-fazil-vk** [comment]
Hi @IzzySoft, thanks for the PR. I just merged it.

**Comment by mu-fazil-vk** [comment]
Hello @shuvashish76 I've just updated the README to fix the shield badge and link. The license is GPL v3.
