### ISSUE TITLE
Choose Piped instance

### ISSUE THREAD

**Issue by shuvashish76** [mu-fazil-vk/FluxTube#15]
Piped instances : https://github.com/TeamPiped/Piped/wiki/Instances
Similar to [LibreTube](https://github.com/libre-tube/LibreTube) add options to change public instance and custom instance.

**Comment by mu-fazil-vk** [comment]
Its added in [latest release](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.7.0)
