### ISSUE TITLE
language

### ISSUE THREAD

**Issue by ShelbyAlan** [mu-fazil-vk/FluxTube#24]
Can add Chinese language?

**Comment by mu-fazil-vk** [comment]
#25 will be merged after making slight changes.

**Comment by mikropsoft** [comment]
> #25 will be merged after making slight changes.

Hello @mu-fazil-vk 

I would very much like you to switch to an arb layout with strings only. This will make the translation simpler.

Like this:

"Home":
"Settings":

---

The arb layout of some apps looks like this, without descriptions. If this is intentional, I would appreciate an answer.

**Comment by ShelbyAlan** [comment]
Thank you for your reply.

**Comment by mu-fazil-vk** [comment]
@mikropsoft I added this translation to [Crowdin](https://crowdin.com/project/fluxtube/invite?h=4d7d9f6ba7c350dc176d6f75a5f569362170999), so you can access it easily.

**Comment by mikropsoft** [comment]
> @mikropsoft I added this translation to [Crowdin](https://crowdin.com/project/fluxtube/invite?h=4d7d9f6ba7c350dc176d6f75a5f569362170999), so you can access it easily.

Thank you. I joined the project with the same username. I would appreciate it if you could give me proofreader permission.

**Comment by mikropsoft** [comment]
@mu-fazil-vk 

Thank you. I joined the project with the same username. I would appreciate it if you could give me proofreader permission. I will upload updated translations.

**Comment by mu-fazil-vk** [comment]
@mikropsoft Done 👍
