### ISSUE TITLE
Proper handling of escape sequences in comment section

### ISSUE THREAD

**Issue by un-logic** [mu-fazil-vk/FluxTube#26]
Version 0.6.9
YouTube comments HTML code contains escaping characters that are not being properly converted into corresponding characters (e.g. `&amp;` is **&** and `&apos;` is **'**).
See screenshot below:
![20240801_140027](https://github.com/user-attachments/assets/5ce0af52-c5a9-4365-8824-4d0fc75ac722)
This sequences makes it hard to read comments. Please fix the code to perform proper conversion.

**Comment by mu-fazil-vk** [comment]
Its fixed on [latest release](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.7.0)

**Comment by un-logic** [comment]
Indeed, v0.7.0 fixed the issue.
