### ISSUE TITLE
Duration of all related videos is the same

### ISSUE THREAD

**Issue by un-logic** [mu-fazil-vk/FluxTube#27]
I have decided to create a separate issue, but I guess it's related to #21.

When you play a video, running time (duration) of all videos on a related tab is the same as on the video now playing.

**Comment by mu-fazil-vk** [comment]
Yes, it is. Thank you for noticing, and it will be fixed in the next update.

**Comment by mu-fazil-vk** [comment]
Its fixed on [latest release](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.7.0).
