### ISSUE TITLE
No dates on home page [regression]

### ISSUE THREAD

**Issue by un-logic** [mu-fazil-vk/FluxTube#30]
Unfortunately, v 0.7.0 has brought some regressions: videos listed on Home page all has a 'No date', while ones listed on Trending have proper date formatting. Also date on video's page isn't formatted properly (year-month-day hour:minute AM/PM).

**Comment by hafijulali** [comment]
I did notice 'No date' as well. Let me look into it and hopefully we should get this fixed easily.

**Comment by mu-fazil-vk** [comment]
The reason is that the piped API is not providing the date for the feed section.

**Comment by un-logic** [comment]
OK, considering first part about feed, shouldn't we simply hide it then? It's more of an eyesore if it doesn't convey any meaningful information.
Also, it would be nice if regional date format was respected. IMO, ISO format is fine, but this 12 hour thing is so archaic.
