### ISSUE TITLE
Home page not showing latest videos

### ISSUE THREAD

**Issue by kryoqa** [mu-fazil-vk/FluxTube#41]
Version 0.7.1

IzzyOnDroid repo

The home page is not refreshing (not showing the latest video) even after changing the server. However going to a channel's page shows the latest videos

https://github.com/user-attachments/assets/f6bb8d82-6489-4c46-8423-86d28c92dc86

**Comment by mu-fazil-vk** [comment]
It's related to [Piped](https://github.com/TeamPiped/Piped). Raise this issue in their repository.
