### ISSUE TITLE
proprietary components

### ISSUE THREAD

**Issue by IzzySoft** [mu-fazil-vk/FluxTube#48]
v0.8.0 added 2 proprietary components: Cronet and (most likely as a dependency of that) Google Mobile Services. This essentially makes your app no longer F/LOSS. Was that intended? For now, I have to add the `NonFreeComp` anti-feature (and mention the 2 libs as reason). It would be preferable, though, could you do without them.

**Comment by mu-fazil-vk** [comment]
I'll remove the components and make a new release ASAP. The Cronet inclusion is due to the native_dio_adapter package.

**Comment by IzzySoft** [comment]
Ah, so even Cronet was "dragged in" :see_no_evil: Thanks for your swift action!

**Comment by mu-fazil-vk** [comment]
It's removed in the [latest version](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.8.1).

**Comment by IzzySoft** [comment]
Thanks! Manually triggered an update check and confirmed it's gone, so the AntiFeature is removed with the next sync around 7 pm UTC.
