### ISSUE TITLE
background play

### ISSUE THREAD

**Issue by rsssxd** [mu-fazil-vk/FluxTube#6]
The video should play in the background. Users must navigate between different tabs and videos while the video plays in the background.

**Comment by mu-fazil-vk** [comment]
Its added in the [latest release](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.7.0).

**Comment by rsssxd** [comment]
This is definitely not true. Picture-in-picture mode stops when you exit the app.

Also, background mode is just audio mode. Piped examples have this feature.

![IMG_20240804_142258_819](https://github.com/user-attachments/assets/0c3baa19-9751-4e4f-a4cf-8f51351a4615)
